apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prism-serve.fullname" . }}-worker-topology
  labels:
    {{- include "prism-serve.labels" . | nindent 4 }}
data:
  topology.json: |
    {{- dict "topology_generation" .Values.worker.topologyGeneration "accepted_topology_generation" .Values.gateway.topologyGeneration "endpoints" (dict "p0" (printf "http://%s-p0:%v" (include "prism-serve.fullname" .) .Values.worker.port) "p1" (printf "http://%s-p1:%v" (include "prism-serve.fullname" .) .Values.worker.port) "d0" (printf "http://%s-d0:%v" (include "prism-serve.fullname" .) .Values.worker.port) "d1" (printf "http://%s-d1:%v" (include "prism-serve.fullname" .) .Values.worker.port)) | toJson | nindent 4 }}
  initialize-state.json: |
    {{- .Values.worker.initializationStateJson | toJson | nindent 4 }}
  {{- with .Values.worker.startupPermitJson }}
  startup-permit.json: |
    {{- . | toJson | nindent 4 }}
  {{- end }}
